photomanager/apps/albums/urls.py
from django.urls import path

from . import views

app_name = "albums"

urlpatterns = [
    path("", views.AlbumListView.as_view(), name="list"),
    path("create", views.AlbumCreateView.as_view(), name="create"),
    path("<uuid:album_id>", views.view_album, name="display"),
    path("<uuid:pk>/edit", views.AlbumEditView.as_view(), name="edit"),
    path("<uuid:pk>/delete", views.AlbumDeleteView.as_view(), name="delete"),
    path(
        "<uuid:album_id>/share/<uuid:share_album_id>",
        views.view_album_share,
        name="share_display",
    ),
    path(
        "<uuid:album_id>/share/links",
        views.AlbumShareLinkList.as_view(),
        name="share_links",
    ),
    path(
        "<uuid:album_id>/share/links/create",
        views.album_share_link_create,
        name="share_links_create",
    ),
    path(
        "<uuid:album_id>/share/links/delete/<uuid:pk>",
        views.AlbumShareLinkDelete.as_view(),
        name="share_links_delete",
    ),
    path(
        "<uuid:album_id>/share/links/edit/<uuid:pk>",
        views.AlbumShareLinkEdit.as_view(),
        name="share_links_edit",
    ),
]

photomanager/apps/photos/urls.py
from django.urls import path

from . import views

app_name = "photos"

urlpatterns = [
    path("rescan", views.rescan_directory, name="rescan"),
    path("reprocess/<uuid:image_id>", views.reprocess_file, name="reprocess"),
    path("raw_image/<uuid:image_id>", views.get_raw_image, name="raw_image"),
    path(
        "raw_image/<uuid:image_id>/album_share/<uuid:album_share_id>",
        views.get_raw_image_album_share,
        name="raw_image_album_share",
    ),
    path("<uuid:image_id>", views.view_single_photo, name="view_single_photo"),
    path(
        "<uuid:image_id>/album_share/<uuid:album_share_id>",
        views.view_single_photo_album_share,
        name="view_single_photo_album_share",
    ),
    path("update/<uuid:pk>", views.PhotoUpdate.as_view(), name="update_photo"),
]

photomanager/urls.py
from django.conf.urls import url
from django.contrib import admin
from django.contrib.auth.views import LogoutView
from django.urls import include, path

from photomanager.apps.albums import urls as albums_urls
from photomanager.apps.photos import urls as photos_urls
from photomanager.apps.photos import views as photos_views

urlpatterns = [
    path("admin/", admin.site.urls),
    path("photos/", include(photos_urls)),
    path("albums/", include(albums_urls)),
    path("", photos_views.IndexView.as_view(), name="index"),
    path("logout", LogoutView.as_view(), name="logout"),
    url("", include("social_django.urls", namespace="social")),
]

photomanager/apps/albums/models.py
import uuid

from django.db import models

from ..photos.models import Photo
from ..users.models import User


class Album(models.Model):
    """
    Represents an album; a collection of photos.
    """

    id = models.UUIDField(primary_key=True, default=uuid.uuid4, editable=False)
    owner = models.ForeignKey(
        User, help_text="The user that this album belongs to.", on_delete=models.CASCADE
    )

    name = models.CharField(
        max_length=300, help_text="Name for this album.", blank=False, null=False
    )
    description = models.TextField(help_text="Description for this album.", blank=True)

    creation_time = models.DateTimeField(
        auto_now_add=True, help_text="Album creation time.", null=True
    )
    last_modified_time = models.DateTimeField(
        auto_now=True, help_text="Album modification time.", null=True
    )

    publicly_accessible = models.BooleanField(
        default=False,
        null=False,
        help_text="Whether this album is publicly accessible. If checked, this album is "
        "listed on the front page and accessible without authentication. The photos within this album "
        "are not visible on the front page, however, they are publicly accessible with their link.",
    )

    photos = models.ManyToManyField(Photo, blank=True)


class AlbumShareLink(models.Model):
    id = models.UUIDField(primary_key=True, default=uuid.uuid4, editable=False)
    album = models.ForeignKey(Album, on_delete=models.CASCADE)

    description = models.CharField(max_length=1000, blank=True)

    # Currently, this may seem useless (just read the creator from the album), but
    # in the future when user to user sharing is implemented, this may be useful.
    creator = models.ForeignKey(
        User, help_text="Creator of this Album share link", on_delete=models.CASCADE
    )

    creation_time = models.DateTimeField(
        auto_now_add=True, help_text="Album share link creation time.", null=True
    )

photomanager/apps/albums/views.py
from django.conf import settings
from django.contrib import messages
from django.contrib.auth.decorators import login_required
from django.contrib.auth.mixins import LoginRequiredMixin, UserPassesTestMixin
from django.http import HttpResponse, HttpResponseForbidden
from django.shortcuts import get_object_or_404, redirect, render
from django.urls import reverse_lazy
from django.views.decorators.http import require_POST
from django.views.generic import CreateView, DeleteView, ListView, UpdateView

from photomanager.apps.albums.models import Album, AlbumShareLink


def view_album(request, album_id: str) -> HttpResponse:
    """
    View for viewing an album.

    :param request: Request object
    :param album_id: ID of an album (a UUID)
    :return: an HTTP response
    """
    album = get_object_or_404(Album, id=album_id)

    if not album.publicly_accessible:
        if not request.user.is_authenticated:
            return redirect(settings.LOGIN_URL)
        if album.owner != request.user:
            return HttpResponseForbidden()

    context = {
        "album": album,
        "photos": album.photos.all().order_by("photo_taken_time"),
    }

    return render(request, "albums/view_single_album.html", context=context)


def view_album_share(request, album_id: str, share_album_id: str) -> HttpResponse:
    album_share_link = get_object_or_404(
        AlbumShareLink, id=share_album_id, album__id=album_id
    )

    album = album_share_link.album

    context = {
        "album": album,
        "photos": album.photos.all().order_by("photo_taken_time"),
        "album_share_id": share_album_id,
    }

    return render(request, "albums/view_single_album.html", context=context)


class AlbumEditView(LoginRequiredMixin, UserPassesTestMixin, UpdateView):
    model = Album
    fields = ["name", "description", "publicly_accessible", "photos"]
    template_name_suffix = "_update"

    def get_success_url(self):
        return reverse_lazy("albums:display", kwargs={"album_id": self.kwargs["pk"]})

    def test_func(self):
        return get_object_or_404(Album, id=self.kwargs["pk"]).owner == self.request.user


class AlbumCreateView(LoginRequiredMixin, CreateView):
    model = Album
    fields = ["name", "description", "publicly_accessible", "photos"]

    def get_success_url(self):
        return reverse_lazy("albums:display", kwargs={"album_id": self.object.id})

    def form_valid(self, form):
        form.instance.owner = self.request.user
        return super(AlbumCreateView, self).form_valid(form)


class AlbumListView(ListView):
    model = Album
    paginate_by = 25

    def get_queryset(self):
        if not self.request.user.is_authenticated:
            return Album.objects.filter(publicly_accessible=True).order_by(
                "-creation_time"
            )
        else:
            return Album.objects.filter(owner=self.request.user).order_by(
                "-creation_time"
            )


class AlbumDeleteView(LoginRequiredMixin, UserPassesTestMixin, DeleteView):
    model = Album
    success_url = reverse_lazy("albums:list")

    def test_func(self):
        return get_object_or_404(Album, id=self.kwargs["pk"]).owner == self.request.user


@login_required
@require_POST
def album_share_link_create(request, album_id: str) -> HttpResponse:
    album = get_object_or_404(Album, id=album_id)

    if request.user != album.owner:
        return HttpResponseForbidden()

    AlbumShareLink.objects.create(album=album, creator=request.user)

    messages.success(request, "Share link successfully created.")

    return redirect(reverse_lazy("albums:share_links", kwargs={"album_id": album_id}))


class AlbumShareLinkList(LoginRequiredMixin, UserPassesTestMixin, ListView):
    model = AlbumShareLink
    paginate_by = 25

    def get_context_data(self, *, object_list=None, **kwargs):
        context = super().get_context_data(**kwargs)
        context["album"] = get_object_or_404(Album, id=self.kwargs["album_id"])
        return context

    def test_func(self):
        return (
            get_object_or_404(Album, id=self.kwargs["album_id"]).owner
            == self.request.user
        )

    def get_queryset(self):
        return AlbumShareLink.objects.filter(
            album=get_object_or_404(Album, id=self.kwargs["album_id"])
        ).order_by("-creation_time")


class AlbumShareLinkDelete(LoginRequiredMixin, UserPassesTestMixin, DeleteView):
    model = AlbumShareLink

    def get_success_url(self):
        return reverse_lazy(
            "albums:share_links", kwargs={"album_id": self.kwargs["album_id"]}
        )

    def test_func(self):
        return (
            get_object_or_404(AlbumShareLink, id=self.kwargs["pk"]).album.owner
            == self.request.user
        )


class AlbumShareLinkEdit(LoginRequiredMixin, UserPassesTestMixin, UpdateView):
    model = AlbumShareLink
    fields = ["description"]
    template_name_suffix = "_update"

    def get_success_url(self):
        return reverse_lazy(
            "albums:share_links", kwargs={"album_id": self.kwargs["album_id"]}
        )

    def test_func(self):
        return (
            get_object_or_404(AlbumShareLink, id=self.kwargs["pk"]).album.owner
            == self.request.user
        )

photomanager/apps/photos/views.py
import base64
import io
import json
import os
import subprocess
from pathlib import Path

from django.conf import settings
from django.contrib import messages
from django.contrib.auth.decorators import login_required
from django.contrib.auth.mixins import UserPassesTestMixin
from django.http import (
    FileResponse,
    HttpResponse,
    HttpResponseForbidden,
    HttpResponseNotFound,
    HttpResponseServerError,
)
from django.shortcuts import get_object_or_404, redirect, render
from django.urls import reverse_lazy
from django.views.decorators.http import require_POST
from django.views.generic import ListView
from django.views.generic.edit import UpdateView
from hurry.filesize import size

from ..albums.models import Album, AlbumShareLink
from .models import Photo
from .tasks import process_image, scan_dir_for_changes


@login_required
def rescan_directory(request):
    scan_dir_for_changes.delay(request.user.subdirectory, request.user.username)
    return HttpResponse("OK")


@login_required
@require_POST
def reprocess_file(request, image_id):
    photo = get_object_or_404(Photo, id=image_id)

    if photo.user != request.user:
        return HttpResponseForbidden()

    process_image.delay(photo.id)
    messages.success(request, "EXIF metadata refresh queued.")
    return redirect(
        reverse_lazy("photos:view_single_photo", kwargs={"image_id": photo.id})
    )


def _get_raw_image(request, photo: Photo) -> FileResponse:
    """
    Backend method for getting a raw image.

    :param request: Request object
    :param photo: Photo object
    :return: FileResponse
    """
    # Read file
    READ_FILE_PATH = os.path.join(
        os.path.dirname(os.path.dirname(os.path.dirname(__file__))),
        "utils/files/read_file.py",
    )

    # If this is a thumbnail we are reading, we will want to use a
    # different file path than if we are reading the actual file

    if request.GET.get("thumbnail"):
        file_to_read = os.path.join(
            settings.IMAGE_THUMBS_DIR,
            str(photo.id)[0],
            str(photo.id)[1],
            f"{str(photo.id)}.thumb.jpeg",
        )
    else:
        file_to_read = photo.file

    file_read: dict = json.loads(
        subprocess.run(
            (["sudo"] if os.getuid() != 0 else [])
            + [
                "pipenv",
                "run",
                "python3",
                READ_FILE_PATH,
                file_to_read,
            ],  # sudo required for chroot
            capture_output=True,
            text=True,
        ).stdout
    )

    if "error" in file_read.keys():
        if file_read["error"] == 404:
            return HttpResponseNotFound()
        elif file_read["error"] == 500:
            return HttpResponseServerError()

    return FileResponse(
        io.BytesIO(base64.b64decode(file_read[file_to_read]["data"])),
        filename=Path(file_to_read).name,
        content_type=file_read[file_to_read]["mime"],
    )


def get_raw_image(request, image_id) -> HttpResponse:
    """
    Returns the image specified by image_id
    :param request: Django request
    :param image_id: Image ID to request
    :return: FileResponse, or HttpResponse for 403s
    """

    photo = get_object_or_404(Photo, id=image_id)

    if not photo.publicly_accessible:
        # Check if this photo is a part of any publicly visible albums.
        if Album.objects.filter(photos=photo, publicly_accessible=True).count() == 0:
            if not request.user.is_authenticated:
                return redirect(settings.LOGIN_URL)

            if photo.user != request.user:
                return HttpResponseForbidden()

    return _get_raw_image(request, photo)


def get_raw_image_album_share(request, image_id, album_share_id) -> HttpResponse:
    """
    Returns the image specified, but authenticated with an album share ID

    :param request: Request object
    :param image_id: ID (UUID) for an image
    :param album_share_id: Album share ID (UUID)
    :return: FileResponse, or HttpResponse for 403s
    """
    photo = get_object_or_404(Photo, id=image_id)
    album_share_link = get_object_or_404(AlbumShareLink, id=album_share_id)

    if photo not in album_share_link.album.photos.all():
        return HttpResponseForbidden()

    return _get_raw_image(request, photo)


def _view_single_photo(
    request, photo: Photo, album_share_id: str = None
) -> HttpResponse:
    """
    Backend method to render single photo page

    :param request: Request object
    :param photo: Photo object
    :param album_share_id: Album share link, if it is to be included
    :return: HttpResponse
    """

    # Find the albums that this photo is a part of
    album_queryset_list = []
    if request.user.is_authenticated:
        album_queryset_list.append(
            Album.objects.filter(photos=photo, owner=request.user)
        )

    if album_share_id:
        album_queryset_list.append(
            Album.objects.filter(
                photos=photo,
                id=get_object_or_404(AlbumShareLink, id=album_share_id).album.id,
            )
        )

    albums = Album.objects.filter(photos=photo, publicly_accessible=True).union(
        *album_queryset_list
    )

    context = {
        "photo": photo,
        "size_hurry": None,
        "album_share_id": album_share_id,
        "license": Photo.License(photo.license).label,
        "albums": albums,
    }

    try:
        context["size_hurry"] = size(photo.image_size)
    except Exception:
        pass

    return render(request, "photos/view_single_photo.html", context=context)


def view_single_photo(request, image_id: str) -> HttpResponse:
    """
    View for a single photo

    :param request: Request object
    :param image_id: ID (UUID) for an image
    :return: HttpResponse
    """
    photo = get_object_or_404(Photo, id=image_id)

    if not photo.publicly_accessible:
        # Check if this photo is a part of any publicly visible albums.
        if Album.objects.filter(photos=photo, publicly_accessible=True).count() == 0:
            if not request.user.is_authenticated:
                return redirect(settings.LOGIN_URL)

            if photo.user != request.user:
                return HttpResponseForbidden()

    return _view_single_photo(request, photo)


def view_single_photo_album_share(request, image_id, album_share_id):
    """
    View for a single photo, but authenticated with an album share ID

    :param request: Request object
    :param image_id: ID (UUID) for an image
    :param album_share_id: Album share ID (UUID)
    :return: HttpResponse
    """
    photo = get_object_or_404(Photo, id=image_id)
    album_share_link = get_object_or_404(AlbumShareLink, id=album_share_id)

    if photo not in album_share_link.album.photos.all():
        return HttpResponseForbidden()

    return _view_single_photo(request, photo, album_share_id=album_share_id)


class PhotoUpdate(UserPassesTestMixin, UpdateView):
    model = Photo
    fields = ["description", "tags", "license", "publicly_accessible"]
    template_name = "photos/photo_update.html"

    def test_func(self):
        return self.request.user == self.get_object().user

    def get_success_url(self):
        # https://stackoverflow.com/a/64108595/2034128
        pk = self.kwargs["pk"]
        return reverse_lazy("photos:view_single_photo", kwargs={"image_id": pk})


class IndexView(ListView):
    model = Photo
    paginate_by = 100

    def get_queryset(self):
        if not self.request.user.is_authenticated:
            return Photo.objects.filter(publicly_accessible=True).order_by(
                "-photo_taken_time"
            )
        else:
            return Photo.objects.filter(user=self.request.user).order_by(
                "-photo_taken_time"
            )

photomanager/templates/albums/album_confirm_delete.html
{% extends "base.html" %}

{% block titleprefix %}Confirm Delete Album{% endblock %}

{% block content %}
    <h2>Confirm Deletion</h2>
    <form method="post">
        <p>
            Are you sure you want to delete the album {{ object.name }}, consisting of {{ object.photos.count }}
            photo{{ object.photos.count|pluralize }}?
        </p>
        {% if object.photos.count > 0 %}
            <p>
                The {{ object.photos.count }} photo{{ object.photos.count|pluralize }} will remain intact.
            </p>
        {% endif %}
        {% csrf_token %}
        <input type="submit" class="btn btn-danger" value="Yes, delete">
    </form>
{% endblock %}

photomanager/templates/albums/album_form.html
{% extends "base.html" %}

{% load crispy_forms_tags %}

{% block content %}
    <h2>Create Album</h2>
    <form method="post">
        {{ form|crispy }}
        {% csrf_token %}
        <input type="submit" value="Create" class="btn btn-success">
    </form>
{% endblock %}

photomanager/templates/albums/album_list.html
{% extends "base.html" %}

{% load bootstrap_pagination %}

{% block titleprefix %}Albums{% endblock %}

{% block content %}
    <div class="container-fluid">
        <h2>Albums</h2>
        {% if user.is_authenticated %}
            <div class="container-fluid pt-3">
                <a href="{% url "albums:create" %}" class="btn btn-outline-success">Create New Album</a>
            </div>
        {% endif %}
        <div class="container-fluid pt-3">
            <table class="table">
                <thead>
                    <tr>
                        <th scope="col">Name</th>
                        <th scope="col"></th>   {# Contains buttons, but we don't want a header #}
                    </tr>
                </thead>
                <tbody>
                    {% for album in object_list %}
                        <tr>
                            <td><a href="{% url "albums:display" album.id %}">{{ album.name }}</a></td>
                            <td>
                                {% if user.is_authenticated and user == album.owner %}
                                    {# Edit album #}
                                    <a href="{% url "albums:edit" album.id %}" class="btn btn-outline-warning" aria-label="Edit">
                                        <i class="fas fa-pencil-alt"></i>
                                    </a>
                                    {# Delete album #}
                                    <a href="{% url "albums:delete" album.id %}" class="btn btn-outline-danger" aria-label="Delete">
                                        <i class="far fa-trash-alt"></i>
                                    </a>
                                {% endif %}
                            </td>
                        </tr>
                    {% empty %}
                        <tr>
                            <td>There are no albums to display.</td>
                            <td></td>
                        </tr>
                    {% endfor %}
                </tbody>
            </table>
        </div>
        <div class="row py-3">
            <div class="col justify-content-center">
                {% bootstrap_paginate page_obj range=10 extra_pagination_classes="justify-content-center" %}
            </div>
        </div>
    </div>
{% endblock %}

photomanager/templates/albums/album_update.html
{% extends "base.html" %}

{% load crispy_forms_tags %}

{% block content %}
    <h2>Update Album</h2>
    <form method="post">
        {{ form|crispy }}
        {% csrf_token %}
        <input type="submit" value="Update" class="btn btn-success">
    </form>
{% endblock %}

photomanager/templates/albums/albumsharelink_confirm_delete.html
{% extends "base.html" %}

{% block titleprefix %}Confirm Delete Share Link{% endblock %}

{% block content %}
    <h2>Confirm Deletion</h2>
    <form method="post">
        <p>
            Are you sure you want to delete the share link
            <a href="{% url "albums:share_display" object.album.id object.id %}">
                {{ request.get_host }}{% url "albums:share_display" object.album.id object.id %}
            </a>, corresponding to the album {{ object.album.name }}?
        </p>
        {% csrf_token %}
        <input type="submit" class="btn btn-danger" value="Yes, delete">
    </form>
{% endblock %}

photomanager/templates/albums/albumsharelink_list.html
{% extends "albums/base.html" %}

{% load bootstrap_pagination %}

{% block titleprefix %}List Share Links - {{ album.name }}{% endblock %}

{% block album_content %}
    <h2>Share Links</h2>
    <p>Share these links to grant public access to albums and their photos.</p>

    <div class="row">
        <div class="col">
            <form action="{% url "albums:share_links_create" album.id %}" method="post">
                {% csrf_token %}
                <input type="submit" class="btn btn-outline-success" value="Create New Share Link" />
            </form>
        </div>
    </div>

    <div class="row pt-3">
        <div class="col">
            <table class="table">
                <thead>
                    <tr>
                        <th scope="col">Share Link</th>
                        <th scope="col">Description</th>
                        <th scope="col"></th>
                    </tr>
                </thead>
                <tbody>
                    {% for link in object_list %}
                        <tr>
                            <td>
                                <a href="{% url "albums:share_display" album.id link.id %}">
                                    {{ request.get_host }}{% url "albums:share_display" album.id link.id %}
                                </a>
                            </td>
                            <td>{{ link.description }}</td>
                            <td>
                                {# Edit link #}
                                <a href="{% url "albums:share_links_edit" album.id link.id %}" class="btn btn-outline-warning" aria-label="Edit">
                                    <i class="fas fa-pencil-alt"></i>
                                </a>
                                {# Delete link #}
                                <a href="{% url "albums:share_links_delete" album.id link.id %}" class="btn btn-outline-danger" aria-label="Delete">
                                    <i class="far fa-trash-alt"></i>
                                </a>
                            </td>
                        </tr>
                    {% empty %}
                        <tr>
                            <td>There are no share links.</td>
                            <td></td>
                            <td></td>
                        </tr>
                    {% endfor %}
                </tbody>
            </table>
        </div>
    </div>

    <div class="row py-3">
        <div class="col justify-content-center">
            {% bootstrap_paginate page_obj range=10 extra_pagination_classes="justify-content-center" %}
        </div>
    </div>

{% endblock %}

photomanager/templates/albums/albumsharelink_update.html
{% extends "base.html" %}

{% load crispy_forms_tags %}

{% block content %}
    <h2>Update Share Link</h2>
    <form method="post">
        {{ form|crispy }}
        {% csrf_token %}
        <input type="submit" value="Update" class="btn btn-success">
    </form>
{% endblock %}

photomanager/templates/albums/base.html
{% extends "base.html" %}

{% block content %}
    <div class="jumbotron">
        <div class="container">
            <h1 class="display-4"><a href="{% if album_share_id %}
                                                {% url "albums:share_display" album.id album_share_id %}
                                            {% else %}
                                                {% url "albums:display" album.id %}
                                            {% endif %}">{{ album.name }}</a></h1>
            <p class="lead">{{ album.description }}</p>
            {% if user.is_authenticated %}
                <div class="row">
                    <div class="col">
                        <a href="{% url "albums:share_links" album.id %}" class="btn btn-outline-primary">View Share Links</a>
                        <a href="{% url "albums:edit" album.id %}" class="btn btn-outline-primary">Edit</a>
                    </div>
                </div>
            {% endif %}
        </div>
    </div>
    {% block album_content %}{% endblock %}
{% endblock %}

photomanager/templates/albums/view_single_album.html
{% extends "albums/base.html" %}

{% load tz %}

{% block titleprefix %}View Album - {{ album.name }}{% endblock %}

{% block album_content %}
    <div class="container-fluid">
        <div class="row py-3">
            {% for photo in photos %}
                <div class="col align-self-center">
                    <div class="card border-0">
                        <a href="{% if album_share_id %}
                                    {% url "photos:view_single_photo_album_share" photo.id album_share_id %}
                                {% else %}
                                    {% url "photos:view_single_photo" photo.id %}
                                {% endif %}">
                            <div class="spinner-wrapper">
                                <div class="d-flex justify-content-center">
                                    <div class="spinner-border" role="status">
                                        <span class="sr-only">Loading...</span>
                                    </div>
                                </div>
                            </div>
                            <img data-src="{% if album_share_id %}
                                        {% url "photos:raw_image_album_share" photo.id album_share_id %}?thumbnail=thumbnail
                                    {% else %}
                                        {% url "photos:raw_image" photo.id %}?thumbnail=thumbnail
                                    {% endif %}" class="img-fluid lazy img-spinner-lazy">
                        </a>
                    </div>
                </div>
                {% if not forloop.last and forloop.counter|divisibleby:3 %}
                    {# Close out the row and start a new one #}
                    </div>
                    <div class="row py-3">
                {% endif %}
            {% empty %}
                <div class="col">
                    <p>There are no photos in this album.</p>
                </div>
            {% endfor %}
        </div>
    </div>
{% endblock %}