photomanager/apps/albums/urls.py
from django.urls import path

from . import views

app_name = "albums"

urlpatterns = [
    path("", views.AlbumListView.as_view(), name="list"),
    path("create", views.AlbumCreateView.as_view(), name="create"),
    path("<uuid:album_id>", views.view_album, name="display"),
    path("<uuid:pk>/edit", views.AlbumEditView.as_view(), name="edit"),
    path("<uuid:pk>/delete", views.AlbumDeleteView.as_view(), name="delete"),
    path(
        "<uuid:album_id>/share/<uuid:share_album_id>",
        views.view_album_share,
        name="share_display",
    ),
    path(
        "<uuid:album_id>/share/links",
        views.AlbumShareLinkList.as_view(),
        name="share_links",
    ),
    path(
        "<uuid:album_id>/share/links/create",
        views.album_share_link_create,
        name="share_links_create",
    ),
    path(
        "<uuid:album_id>/share/links/delete/<uuid:pk>",
        views.AlbumShareLinkDelete.as_view(),
        name="share_links_delete",
    ),
    path(
        "<uuid:album_id>/share/links/edit/<uuid:pk>",
        views.AlbumShareLinkEdit.as_view(),
        name="share_links_edit",
    ),
]

photomanager/apps/photos/urls.py
from django.urls import path

from . import views

app_name = "photos"

urlpatterns = [
    path("rescan", views.rescan_directory, name="rescan"),
    path("reprocess/<uuid:image_id>", views.reprocess_file, name="reprocess"),
    path("raw_image/<uuid:image_id>", views.get_raw_image, name="raw_image"),
    path(
        "raw_image/<uuid:image_id>/album_share/<uuid:album_share_id>",
        views.get_raw_image_album_share,
        name="raw_image_album_share",
    ),
    path("<uuid:image_id>", views.view_single_photo, name="view_single_photo"),
    path(
        "<uuid:image_id>/album_share/<uuid:album_share_id>",
        views.view_single_photo_album_share,
        name="view_single_photo_album_share",
    ),
    path("update/<uuid:pk>", views.PhotoUpdate.as_view(), name="update_photo"),
]

photomanager/urls.py
from django.conf.urls import url
from django.contrib import admin
from django.contrib.auth.views import LogoutView
from django.urls import include, path

from photomanager.apps.albums import urls as albums_urls
from photomanager.apps.photos import urls as photos_urls
from photomanager.apps.photos import views as photos_views

urlpatterns = [
    path("admin/", admin.site.urls),
    path("photos/", include(photos_urls)),
    path("albums/", include(albums_urls)),
    path("", photos_views.IndexView.as_view(), name="index"),
    path("logout", LogoutView.as_view(), name="logout"),
    url("", include("social_django.urls", namespace="social")),
]

photomanager/apps/albums/models.py
import uuid

from django.db import models

from ..photos.models import Photo
from ..users.models import User


class Album(models.Model):
    """
    Represents an album; a collection of photos.
    """

    id = models.UUIDField(primary_key=True, default=uuid.uuid4, editable=False)
    owner = models.ForeignKey(
        User, help_text="The user that this album belongs to.", on_delete=models.CASCADE
    )

    name = models.CharField(
        max_length=300, help_text="Name for this album.", blank=False, null=False
    )
    description = models.TextField(help_text="Description for this album.", blank=True)

    creation_time = models.DateTimeField(
        auto_now_add=True, help_text="Album creation time.", null=True
    )
    last_modified_time = models.DateTimeField(
        auto_now=True, help_text="Album modification time.", null=True
    )

    publicly_accessible = models.BooleanField(
        default=False,
        null=False,
        help_text="Whether this album is publicly accessible. If checked, this album is "
        "listed on the front page and accessible without authentication. The photos within this album "
        "are not visible on the front page, however, they are publicly accessible with their link.",
    )

    photos = models.ManyToManyField(Photo, blank=True)


class AlbumShareLink(models.Model):
    id = models.UUIDField(primary_key=True, default=uuid.uuid4, editable=False)
    album = models.ForeignKey(Album, on_delete=models.CASCADE)

    description = models.CharField(max_length=1000, blank=True)

    # Currently, this may seem useless (just read the creator from the album), but
    # in the future when user to user sharing is implemented, this may be useful.
    creator = models.ForeignKey(
        User, help_text="Creator of this Album share link", on_delete=models.CASCADE
    )

    creation_time = models.DateTimeField(
        auto_now_add=True, help_text="Album share link creation time.", null=True
    )

photomanager/apps/albums/views.py
from django.conf import settings
from django.contrib import messages
from django.contrib.auth.decorators import login_required
from django.contrib.auth.mixins import LoginRequiredMixin, UserPassesTestMixin
from django.http import HttpResponse, HttpResponseForbidden
from django.shortcuts import get_object_or_404, redirect, render
from django.urls import reverse_lazy
from django.views.decorators.http import require_POST
from django.views.generic import CreateView, DeleteView, ListView, UpdateView

from photomanager.apps.albums.models import Album, AlbumShareLink


def view_album(request, album_id: str) -> HttpResponse:
    """
    View for viewing an album.

    :param request: Request object
    :param album_id: ID of an album (a UUID)
    :return: an HTTP response
    """
    album = get_object_or_404(Album, id=album_id)

    if not album.publicly_accessible:
        if not request.user.is_authenticated:
            return redirect(settings.LOGIN_URL)
        if album.owner != request.user:
            return HttpResponseForbidden()

    context = {
        "album": album,
        "photos": album.photos.all().order_by("photo_taken_time"),
    }

    return render(request, "albums/view_single_album.html", context=context)


def view_album_share(request, album_id: str, share_album_id: str) -> HttpResponse:
    album_share_link = get_object_or_404(
        AlbumShareLink, id=share_album_id, album__id=album_id
    )

    album = album_share_link.album

    context = {
        "album": album,
        "photos": album.photos.all().order_by("photo_taken_time"),
        "album_share_id": share_album_id,
    }

    return render(request, "albums/view_single_album.html", context=context)


class AlbumEditView(LoginRequiredMixin, UserPassesTestMixin, UpdateView):
    model = Album
    fields = ["name", "description", "publicly_accessible", "photos"]
    template_name_suffix = "_update"

    def get_success_url(self):
        return reverse_lazy("albums:display", kwargs={"album_id": self.kwargs["pk"]})

    def test_func(self):
        return get_object_or_404(Album, id=self.kwargs["pk"]).owner == self.request.user


class AlbumCreateView(LoginRequiredMixin, CreateView):
    model = Album
    fields = ["name", "description", "publicly_accessible", "photos"]

    def get_success_url(self):
        return reverse_lazy("albums:display", kwargs={"album_id": self.object.id})

    def form_valid(self, form):
        form.instance.owner = self.request.user
        return super(AlbumCreateView, self).form_valid(form)


class AlbumListView(ListView):
    model = Album
    paginate_by = 25

    def get_queryset(self):
        if not self.request.user.is_authenticated:
            return Album.objects.filter(publicly_accessible=True).order_by(
                "-creation_time"
            )
        else:
            return Album.objects.filter(owner=self.request.user).order_by(
                "-creation_time"
            )


class AlbumDeleteView(LoginRequiredMixin, UserPassesTestMixin, DeleteView):
    model = Album
    success_url = reverse_lazy("albums:list")

    def test_func(self):
        return get_object_or_404(Album, id=self.kwargs["pk"]).owner == self.request.user


@login_required
@require_POST
def album_share_link_create(request, album_id: str) -> HttpResponse:
    album = get_object_or_404(Album, id=album_id)

    if request.user != album.owner:
        return HttpResponseForbidden()

    AlbumShareLink.objects.create(album=album, creator=request.user)

    messages.success(request, "Share link successfully created.")

    return redirect(reverse_lazy("albums:share_links", kwargs={"album_id": album_id}))


class AlbumShareLinkList(LoginRequiredMixin, UserPassesTestMixin, ListView):
    model = AlbumShareLink
    paginate_by = 25

    def get_context_data(self, *, object_list=None, **kwargs):
        context = super().get_context_data(**kwargs)
        context["album"] = get_object_or_404(Album, id=self.kwargs["album_id"])
        return context

    def test_func(self):
        return (
            get_object_or_404(Album, id=self.kwargs["album_id"]).owner
            == self.request.user
        )

    def get_queryset(self):
        return AlbumShareLink.objects.filter(
            album=get_object_or_404(Album, id=self.kwargs["album_id"])
        ).order_by("-creation_time")


class AlbumShareLinkDelete(LoginRequiredMixin, UserPassesTestMixin, DeleteView):
    model = AlbumShareLink

    def get_success_url(self):
        return reverse_lazy(
            "albums:share_links", kwargs={"album_id": self.kwargs["album_id"]}
        )

    def test_func(self):
        return (
            get_object_or_404(AlbumShareLink, id=self.kwargs["pk"]).album.owner
            == self.request.user
        )


class AlbumShareLinkEdit(LoginRequiredMixin, UserPassesTestMixin, UpdateView):
    model = AlbumShareLink
    fields = ["description"]
    template_name_suffix = "_update"

    def get_success_url(self):
        return reverse_lazy(
            "albums:share_links", kwargs={"album_id": self.kwargs["album_id"]}
        )

    def test_func(self):
        return (
            get_object_or_404(AlbumShareLink, id=self.kwargs["pk"]).album.owner
            == self.request.user
        )

photomanager/apps/photos/views.py
import base64
import io
import json
import os
import subprocess
from pathlib import Path

from django.conf import settings
from django.contrib import messages
from django.contrib.auth.decorators import login_required
from django.contrib.auth.mixins import UserPassesTestMixin
from django.http import (
    FileResponse,
    HttpResponse,
    HttpResponseForbidden,
    HttpResponseNotFound,
    HttpResponseServerError,
)
from django.shortcuts import get_object_or_404, redirect, render
from django.urls import reverse_lazy
from django.views.decorators.http import require_POST
from django.views.generic import ListView
from django.views.generic.edit import UpdateView
from hurry.filesize import size

from ..albums.models import Album, AlbumShareLink
from .models import Photo
from .tasks import process_image, scan_dir_for_changes


@login_required
def rescan_directory(request):
    scan_dir_for_changes.delay(request.user.subdirectory, request.user.username)
    return HttpResponse("OK")


@login_required
@require_POST
def reprocess_file(request, image_id):
    photo = get_object_or_404(Photo, id=image_id)

    if photo.user != request.user:
        return HttpResponseForbidden()

    process_image.delay(photo.id)
    messages.success(request, "EXIF metadata refresh queued.")
    return redirect(
        reverse_lazy("photos:view_single_photo", kwargs={"image_id": photo.id})
    )


def _get_raw_image(request, photo: Photo) -> FileResponse:
    """
    Backend method for getting a raw image.

    :param request: Request object
    :param photo: Photo object
    :return: FileResponse
    """
    # Read file
    READ_FILE_PATH = os.path.join(
        os.path.dirname(os.path.dirname(os.path.dirname(__file__))),
        "utils/files/read_file.py",
    )

    # If this is a thumbnail we are reading, we will want to use a
    # different file path than if we are reading the actual file

    if request.GET.get("thumbnail"):
        file_to_read = os.path.join(
            settings.IMAGE_THUMBS_DIR,
            str(photo.id)[0],
            str(photo.id)[1],
            f"{str(photo.id)}.thumb.jpeg",
        )
    else:
        file_to_read = photo.file

    file_read: dict = json.loads(
        subprocess.run(
            (["sudo"] if os.getuid() != 0 else [])
            + [
                "pipenv",
                "run",
                "python3",
                READ_FILE_PATH,
                file_to_read,
            ],  # sudo required for chroot
            capture_output=True,
            text=True,
        ).stdout
    )

    if "error" in file_read.keys():
        if file_read["error"] == 404:
            return HttpResponseNotFound()
        elif file_read["error"] == 500:
            return HttpResponseServerError()

    return FileResponse(
        io.BytesIO(base64.b64decode(file_read[file_to_read]["data"])),
        filename=Path(file_to_read).name,
        content_type=file_read[file_to_read]["mime"],
    )


def get_raw_image(request, image_id) -> HttpResponse:
    """
    Returns the image specified by image_id
    :param request: Django request
    :param image_id: Image ID to request
    :return: FileResponse, or HttpResponse for 403s
    """

    photo = get_object_or_404(Photo, id=image_id)

    if not photo.publicly_accessible:
        # Check if this photo is a part of any publicly visible albums.
        if Album.objects.filter(photos=photo, publicly_accessible=True).count() == 0:
            if not request.user.is_authenticated:
                return redirect(settings.LOGIN_URL)

            if photo.user != request.user:
                return HttpResponseForbidden()

    return _get_raw_image(request, photo)


def get_raw_image_album_share(request, image_id, album_share_id) -> HttpResponse:
    """
    Returns the image specified, but authenticated with an album share ID

    :param request: Request object
    :param image_id: ID (UUID) for an image
    :param album_share_id: Album share ID (UUID)
    :return: FileResponse, or HttpResponse for 403s
    """
    photo = get_object_or_404(Photo, id=image_id)
    album_share_link = get_object_or_404(AlbumShareLink, id=album_share_id)

    if photo not in album_share_link.album.photos.all():
        return HttpResponseForbidden()

    return _get_raw_image(request, photo)


def _view_single_photo(
    request, photo: Photo, album_share_id: str = None
) -> HttpResponse:
    """
    Backend method to render single photo page

    :param request: Request object
    :param photo: Photo object
    :param album_share_id: Album share link, if it is to be included
    :return: HttpResponse
    """

    # Find the albums that this photo is a part of
    album_queryset_list = []
    if request.user.is_authenticated:
        album_queryset_list.append(
            Album.objects.filter(photos=photo, owner=request.user)
        )

    if album_share_id:
        album_queryset_list.append(
            Album.objects.filter(
                photos=photo,
                id=get_object_or_404(AlbumShareLink, id=album_share_id).album.id,
            )
        )

    albums = Album.objects.filter(photos=photo, publicly_accessible=True).union(
        *album_queryset_list
    )

    context = {
        "photo": photo,
        "size_hurry": None,
        "album_share_id": album_share_id,
        "license": Photo.License(photo.license).label,
        "albums": albums,
    }

    try:
        context["size_hurry"] = size(photo.image_size)
    except Exception:
        pass

    return render(request, "photos/view_single_photo.html", context=context)


def view_single_photo(request, image_id: str) -> HttpResponse:
    """
    View for a single photo

    :param request: Request object
    :param image_id: ID (UUID) for an image
    :return: HttpResponse
    """
    photo = get_object_or_404(Photo, id=image_id)

    if not photo.publicly_accessible:
        # Check if this photo is a part of any publicly visible albums.
        if Album.objects.filter(photos=photo, publicly_accessible=True).count() == 0:
            if not request.user.is_authenticated:
                return redirect(settings.LOGIN_URL)

            if photo.user != request.user:
                return HttpResponseForbidden()

    return _view_single_photo(request, photo)


def view_single_photo_album_share(request, image_id, album_share_id):
    """
    View for a single photo, but authenticated with an album share ID

    :param request: Request object
    :param image_id: ID (UUID) for an image
    :param album_share_id: Album share ID (UUID)
    :return: HttpResponse
    """
    photo = get_object_or_404(Photo, id=image_id)
    album_share_link = get_object_or_404(AlbumShareLink, id=album_share_id)

    if photo not in album_share_link.album.photos.all():
        return HttpResponseForbidden()

    return _view_single_photo(request, photo, album_share_id=album_share_id)


class PhotoUpdate(UserPassesTestMixin, UpdateView):
    model = Photo
    fields = ["description", "tags", "license", "publicly_accessible"]
    template_name = "photos/photo_update.html"

    def test_func(self):
        return self.request.user == self.get_object().user

    def get_success_url(self):
        # https://stackoverflow.com/a/64108595/2034128
        pk = self.kwargs["pk"]
        return reverse_lazy("photos:view_single_photo", kwargs={"image_id": pk})


class IndexView(ListView):
    model = Photo
    paginate_by = 100

    def get_queryset(self):
        if not self.request.user.is_authenticated:
            return Photo.objects.filter(publicly_accessible=True).order_by(
                "-photo_taken_time"
            )
        else:
            return Photo.objects.filter(user=self.request.user).order_by(
                "-photo_taken_time"
            )

photomanager/templates/photos/view_single_photo.html
{% extends "base.html" %}

{% load tz %}

{% block titleprefix %}Photo{% endblock %}

{% block content %}
    <div class="container-fluid">
        <div class="row justify-content-center">
            <div class="col-6">
                <div class="card border-0">
                    <a href="#" data-toggle="modal" data-target="#photolightbox">
                        <div class="spinner-wrapper">
                            <div class="d-flex justify-content-center">
                                <div class="spinner-border" role="status">
                                    <span class="sr-only">Loading...</span>
                                </div>
                            </div>
                        </div>
                        <img data-src="{% if album_share_id %}
                                    {% url "photos:raw_image_album_share" photo.id album_share_id %}?thumbnail=thumbnail
                                {% else %}
                                    {% url "photos:raw_image" photo.id %}?thumbnail=thumbnail
                                {% endif %}" class="img-fluid lazy img-spinner-lazy"
                             style="cursor: zoom-in;" aria-describedby="#details-description" />
                    </a>
                </div>
            </div>
        </div>
    </div>

    <div class="container-fluid pt-5">
        <div class="row">
            <div class="col">
                <table class="table table-borderless table-sm">
                    <tbody>
                        {# Description #}
                        <tr>
                            <td><i class="far fa-sticky-note" aria-label="Description of image" aria-details="#details-description"></i></td>
                            <td>
                                <p id="details-description">
                                    {% if photo.description|length > 0 %}
                                        {{ photo.description }}
                                    {% else %}
                                        <i>No description was provided.</i>
                                    {% endif %}
                                </p>
                            </td>
                        </tr>
                        {# Tags #}
                        <tr>
                            <td><i class="fas fa-tags" aria-label="Tags" aria-details="#details-tags"></i></td>
                            <td>
                                <p id="details-tags">
                                    {% for tag in photo.tags.all %}
                                        <a href="#" class="badge badge-primary">{{ tag }}</a>
                                    {% empty %}
                                        There are no tags for this image.
                                    {% endfor %}
                                </p>
                            </td>
                        </tr>
                        {# Albums #}
                        <tr>
                            <td><i class="fas fa-images" aria-label="Albums this image is a part of" aria-details="#details-albums"></i></td>
                            <td>
                                <div id="details-albums">
                                    {% if albums %}
                                        <p>This photo is a part of the following albums:</p>
                                        <ul>
                                            {% for album in albums %}
                                                <li><a href="
                                                    {% if album_share_id %}
                                                        {% url "albums:share_display" album.id album_share_id %}
                                                    {% else %}
                                                        {% url "albums:display" album.id %}
                                                    {% endif %}">{{ album.name }}</a></li>
                                            {% endfor %}
                                        </ul>
                                    {% else %}
                                        <p>This image is not a part of any album.</p>
                                    {% endif %}
                                </div>
                            </td>
                        </tr>
                        {# Public accessibility #}
                        <tr>
                            <td><i class="fas fa-user-friends" aria-label="Is this image publicly accessible?" aria-details="#details-public"></i></td>
                            <td>
                                <p id="details-public">
                                    {% if photo.publicly_accessible %}
                                    This photo is publicly accessible.
                                    {% else %}
                                    This photo is not publicly accessible.
                                    {% endif %}
                                </p>
                            </td>
                        </tr>
                        {% if user == photo.user %}
                        {# Edit link #}
                        <tr>
                            <td><i class="fas fa-pencil-alt" aria-label="Edit links" aria-details="#edit-links"></i></td>
                            <td>
                                <p id="edit-links">
                                    <a class="btn btn-outline-primary" href="{% url "photos:update_photo" photo.id %}">Edit</a>
                                </p>
                            </td>
                        </tr>
                        {% endif %}
                        {# Uploaded by #}
                        <tr>
                            <td><i class="fas fa-user-alt" aria-label="Owner of picture" aria-details="#details-owner"></i></td>
                            <td>
                                <p id="details-owner">
                                    Uploaded by {{ photo.user.username }}
                                </p>
                            </td>
                        </tr>
                        {# License info #}
                        <tr>
                            <td><i class="far fa-copyright" aria-label="Copyright status" aria-details="#details-copyright"></i></td>
                            <td>
                                <p id="details-copyright">
                                    {{ license }}
                                </p>
                            </td>
                        </tr>
                    </tbody>
                </table>
            </div>
            <div class="col">
                <table class="table table-borderless table-sm">
                    <tbody>
                        {% if photo.photo_taken_time %}
                            <tr>
                                <td><i class="far fa-calendar-alt" aria-label="Dates and times for this image" aria-details="#details-date"></i></td>
                                <td>
                                    <div id="details-date">
                                        <p>Taken on {{ photo.photo_taken_time }}</p>
                                        <p>Uploaded on {{ photo.creation_time }}</p>
                                        <p>Last modified {{ photo.last_modified_time }}</p>
                                    </div>
                                </td>
                            </tr>
                        {% endif %}
                        {% if photo.camera_make or photo.camera_model %}
                            <tr>
                                <td><i class="fas fa-camera" aria-label="Taken using" aria-details="#details-camera"></i></td>
                                <td><p id="details-camera">{{ photo.camera_make|title }} {{ photo.camera_model }}</p></td>
                            </tr>
                        {% endif %}
                        {% if photo.aperture_value or photo.shutter_speed_value or photo.focal_length or photo.iso %}
                            <tr>
                                <td>
                                    <i class="fas fa-hourglass-half" aria-label="Further details on image (shutter speed, aperture, etc.)"
                                    aria-details="#details-shutter"></i>
                                </td>
                                <td>
                                    <p id="#details-shutter">
                                        {% if photo.shutter_speed_seconds %}
                                            <span class="pr-2" aria-label="Shutter speed in seconds">{{ photo.shutter_speed_seconds }}"</span>
                                        {% endif %}
                                        {% if photo.aperture_value %}
                                            <span class="pr-2" aria-label="Aperture, f-stop">f/{{ photo.aperture_value_f_stop }}</span>
                                        {% endif %}
                                        {% if photo.focal_length %}
                                            <span class="pr-2" aria-label="Focal length, millimeters">{{ photo.focal_length }}mm</span>
                                        {% endif %}
                                        {% if photo.iso %}
                                            <span class="pr-2" aria-label="ISO">ISO {{ photo.iso }}</span>
                                        {% endif %}
                                    </p>
                                </td>
                            </tr>
                        {% endif %}
                        {# Flash mode compulsory on all EXIF data #}
                            <tr>
                                <td><i class="fas fa-bolt" aria-label="Flash characteristics" aria-details="#details-flash"></i></td>
                                <td>
                                    <p id="details-flash">
                                        <span class="pr-2" aria-label="Did the flash fire?">
                                            {% if photo.flash_fired %}
                                                Flash fired
                                            {% elif photo.flash_fired == None %}
                                                Flash status unknown
                                            {% else %}
                                                Flash did not fire
                                            {% endif %}
                                        </span>
                                        <span class="pr-2" aria-label="Flash mode">
                                            {% if photo.flash_mode == 1 %}
                                                Flash forced
                                            {% elif photo.flash_mode == 2 %}
                                                Flash disabled
                                            {% elif photo.flash_mode == 3 %}
                                                Flash on automatic mode
                                            {% else %}
                                                Flash mode unknown
                                            {% endif %}
                                        </span>
                                    </p>
                                </td>
                            </tr>
                        {% if photo.image_width and photo.image_height and size_hurry %}    {# if image has been processed #}
                            <tr>
                                <td><i class="fas fa-file-image" aria-label="Image file characteristics" aria-details="#details-file"></i></td>
                                <td><p id="details-file">{{ photo.image_width }} &#215; {{ photo.image_height }}, {{ size_hurry }}</p></td>
                            </tr>
                        {% endif %}

                    </tbody>
                </table>
            </div>
        </div>
    </div>

    <div class="modal fade" id="photolightbox" tabindex="-1" aria-hidden="true">
        <div class="modal-dialog modal-xl">
            <div class="modal-content">
                <div class="modal-header">
                    <button type="button" class="close" data-dismiss="modal" aria-label="Close">
                        <span aria-hidden="true">&times;</span>
                    </button>
                </div>
                <div class="modal-body">
                    <div class="container">
                        <div class="row justify-content-center">
                            <div class="col-lg-auto">
                                <div class="spinner-wrapper">
                                    <div class="d-flex justify-content-center">
                                        <div class="spinner-border" role="status">
                                            <span class="sr-only">Loading...</span>
                                        </div>
                                    </div>
                                </div>
                                <img data-src="{% if album_share_id %}
                                    {% url "photos:raw_image_album_share" photo.id album_share_id %}
                                {% else %}
                                    {% url "photos:raw_image" photo.id %}
                                {% endif %}" class="img-fluid lazy img-spinner-lazy" />
                            </div>
                        </div>
                    </div>
                </div>
            </div>
        </div>
    </div>
{% endblock %}